rules:
    short_array_syntax: ~
    max_blank_lines:
        max: 2
    yaml_instead_of_yml_suffix: ~
    composer_dev_option_not_at_the_end: ~
    yarn_dev_option_at_the_end: ~
    versionadded_directive_should_have_version: ~
    unused_links: ~
    filename_uses_underscores_only: ~

# do not report as violation
whitelist:
    regex:
        - '/FOSUserBundle(.*)\.yml/'
        - '/``.yml``/'
        - '/(.*)\.orm\.yml/' # currently DoctrineBundle only supports .yml
    lines:
        - 'in config files, so the old ``app/config/config_dev.yml`` goes to'
        - '#. The most important config file is ``app/config/services.yml``, which now is'
        - 'php "%s/../bin/console" cache:clear --env=%s --no-warmup'
        - 'code in production without a proxy, it becomes trivially easy to abuse your'
