rules:
    #- 'be_kind_to_newcomers'
    - 'blank_line_after_directive'
    - 'blank_line_after_filepath_in_php_code_block'
    - 'no_blank_line_after_filepath_in_yaml_code_block'
    - 'no_blank_line_after_filepath_in_xml_code_block'
    - 'no_blank_line_after_filepath_in_twig_code_block'
    - 'no_app_console'
    - 'no_php_open_tag_in_code_block_php_directive'
    - 'php_prefix_before_bin_console'
    #- 'replacement'
    - 'short_array_syntax'
    #- 'typo'
    - 'yaml_instead_of_yml_suffix'
    - 'composer_dev_option_not_at_the_end'
    - 'yarn_dev_option_at_the_end'
    - 'versionadded_directive_should_have_version'

# do not report as violation
whitelist:
    regex:
        - '/FOSUserBundle(.*)\.yml/'
        - '/``.yml``/'
        - '/(.*)\.orm\.yml/' # currently DoctrineBundle only supports .yml
    lines:
        - 'in config files, so the old ``app/config/config_dev.yml`` goes to'
        - '#. The most important config file is ``app/config/services.yml``, which now is'
        - 'php "%s/../bin/console" cache:clear --env=%s --no-warmup'
        - 'code in production without a proxy, it becomes trivially easy to abuse your'
