on: push
name: Lint
jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.16.1.1
              with:
                  args: --diff --dry-run
